---
name: fish-actions/install-fish

description: Install the latest stable release of fish

branding:
  icon: download
  color: blue

runs:
  using: composite

  steps:
    - if: runner.os == 'Linux'
      run: |
        sudo apt-add-repository --yes --no-update ppa:fish-shell/release-3
        sudo apt-get update -qq
        sudo apt-get install --yes fish
      shell: bash

    - if: runner.os == 'macOS'
      run: brew install fish
      shell: bash
